[package]
name = "rusty-money"
version = "0.3.6"
authors = ["Varun Srinivasan <varunsrin@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/varunsrin/rusty_money"
documentation = "https://docs.rs/rusty-money"
description = """
Money type for Rust.
"""
keywords = ["money", "currency", "iso-4217", "exchange"]
categories = ["data-structures", "rust-patterns"]

[features]
default=["iso", "crypto"]
iso = []
crypto = []


[dependencies]
rust_decimal = "1.8.1"
rust_decimal_macros = "1.8.1"
